### ISSUE TITLE
Discussion of first versions

### ISSUE THREAD

**Issue by jisotalo** [jisotalo/node-red-contrib-ads-client#1]
If you have any comments please add them here. I'm not sure if everything is done correctly (how things usually are done with Node-RED).

If you find bugs and other problems, please submit a new issue.

The library now has three nodes: Read Symbol, Write Symbol and Subscribe. Each one has it's own help inside the Node-RED so check it out.

**Comment by Hopperpop** [comment]
First of all, Thank you for doing this. 

I tried the following test connecting to a local system:
![afbeelding](https://user-images.githubusercontent.com/11853634/118628044-83f4c500-b7cc-11eb-9b89-c2e280f9b9bb.png)

This are my current comments:

- The read/write nodes clear the full message. As far as I know most nodes just copy the full message and modifies what they are interacting on. Example: if you set "msg.topic", it would be handy if you could reuse it in later nodes.
- It can be useful if errors can be caught. See: https://nodered.org/docs/creating-nodes/node-js#handling-errors
- This comment is more about aesthetics: Having the full error message in the status can be "annoying". I can't remember if any other node does it like this. Having a short status message and having the error in the console + catch node seems better to me. (But it's just my opinion, maybe other people thing differently.)
- Being able to name the node for easy reading.

**Comment by jisotalo** [comment]
Thanks for your feedback @Hopperpop! It's very valuable as I haven't got much experience of Node-RED. 

**- The read/write nodes clear the full message. As far as I know most nodes just copy the full message and modifies what they are interacting on. Example: if you set "msg.topic", it would be handy if you could reuse it in later nodes.**

Thanks, I didn't know that. So basically I just need to take the input msg, do the action, and then output the same msg with different payload & possible other new properties?

**- It can be useful if errors can be caught. See: https://nodered.org/docs/creating-nodes/node-js#handling-errors**

I actually tried to do that, but I proably did it wrongly. Did you try to catch the errors? I will check it.

**- This comment is more about aesthetics: Having the full error message in the status can be "annoying". I can't remember if any other node does it like this. Having a short status message and having the error in the console + catch node seems better to me. (But it's just my opinion, maybe other people thing differently.)**
That's true. At first it looked great to me, however when there are longer error messages it's not that good.

Do you think messages like "Subscribed", "Error: Failed to subscribe" etc. would be OK? And keep the error information in console and for catch node? I really have no idea how these are usually used..

**- Being able to name the node for easy reading.**

Do you have any link to show it's done? Thanks.

**Comment by jisotalo** [comment]
> Hi there
> 
> Thanks for your very fast work!
> 
> wanted to test it too. I failed very early on .. :-(
> 
> i can't connect to the PLC, TC2.11 (10.1.121.1; 10.1.121.1.1.1)
> Node-RED: 10.1.121.120
> 
> Where is my mistake?
> 
> I'm running node-red in a docker but don't think this is critical. In other Lib's this works without restrictions ..?

Have you tested the connection with ads-client before? If not, please read the readme of the ads-client, especially [the chapter about connection.](https://github.com/jisotalo/ads-client#connection-setups-and-possibilities)

What is your setup? What operating system are you using?

**Comment by jisotalo** [comment]
I just released a new version. Looking forward for your feedback!

## [1.0.4] - 18.05.2021
### Added
- Name properties to all nodes (also connection config -> PLCs can be named)

### Changed
- `Read Symbol` and `Write Symbol` nodes no longer clear the input message. Instead it's passed onwards.
- Added better support for error catching (`Subscribe` is still probably not working 100% with `Catch` nodes)
- Node status messages are now shorter and more compact
- Minor fixes and corrections

**Comment by Hopperpop** [comment]
Good job! All my points seems to be addressed. 

The error catching works now. For the subscription i see the error catching as less important as it's more an input node. But the status would here be more valuable I think. Currently it stays green (subscribed) when the plc goes into configuration mode. 
For reading/writing you want to know if the action is successful, the catch error is perfect for that. For the subscription you want to know if it has an active subscription. 

Another useful thing would be if you could know the system status before reading/writing. This could be in the form of a system node where you can request/subscribe to the plc/connection status. You could use it for example with this [node](https://flows.nodered.org/node/node-red-contrib-msg-queue), to buffer data if you application needs it.  (This is more as an example what the status could be used for.)

**Comment by hbTecAG** [comment]
> > Hi there
> > Thanks for your very fast work!
> > wanted to test it too. I failed very early on .. :-(
> > i can't connect to the PLC, TC2.11 (10.1.121.1; 10.1.121.1.1.1)
> > Node-RED: 10.1.121.120
> > Where is my mistake?
> > I'm running node-red in a docker but don't think this is critical. In other Lib's this works without restrictions ..?
> 
> @hbTecAG
> Have you tested the connection with ads-client before? If not, please read the readme of the ads-client, especially [the chapter about connection.](https://github.com/jisotalo/ads-client#connection-setups-and-possibilities)
> 
> What is your setup? What operating system are you using?

No, i have never run ads-client bevor. I have study this chapter, but i still have problems..

My Setup: (i Think, thats the 3rd?)
Client: Raspberry pi with Node-RED running in a Docker Container. (10.1.121.120)
PLC: CX5120 Running with TC2.11 Runtime (10.1.121.1)

Configuration see above

**Comment by jisotalo** [comment]
Actually I have never tried to connect from non-Windows system to TwinCAT 2.

Have you added a route manually? Does the TC2 have similar XML file for routes?

**Comment by Hopperpop** [comment]
@hbTecAG 
I have it working on a raspberry pi and docker + remote p(l)c with Twincat 3.1.4024.12.
Steps to get it working:

- Make sure to open port 48898 in the firewall of the remote pc.
- Add a static route to your raspbery pi on the remote p(l)c with a chosen AmsNetId.
- For the rest I used a similar configuration in the node. I only didn't fill in localAdress. If I fill it in, it gives me timeout errors.

Try also different localAdsPort's and don't mix both nodes as they block each others connection (don't forget to disable/delete the configuration nodes.)

**Comment by jisotalo** [comment]
Hi all!

Just updated to version 1.2.0. There is now a new node for connection status.

## [1.2.0] - 30.06.2021
### Added
  - New node `Connection Status` that reports ADS connection status changes
    - Automatically outputs latest connection status when changes detected
    - Can also be read manually using input trigger
    - Outputs true/false (ok/not ok) and connection info
  - New node `Read Runtime State` that implements ads-client library `readPlcRuntimeState()`
    - Possible to read PLC status (run, stop) from Node-RED
  - New node `Read System Manager State` that implements ads-client library `readSystemManagerState()`
    - Possible to read system manager status (run, config) from Node-RED
  - Updated `ADS connection` node
    - Automatically tries to connect to the target PLC in the background
    - Before the connection was retried only when reading/writing/subscribing
    - Now automatically connects when possible -> supports the new `Connection Status` node
  - Updated `Subscribe` node
    - Listens on connection state changes in a better way than before
